= Lattice Based cryptography

== Introduction

Shor's algorithm can break any cryptography based on factorization.

Quantum cryptography is lies to physic of photons/electrons etc...

Post-quantum cryptography is only about mathematics

== Lattice

Set of all integer linear combination of linearly independent basis vectors.

Lattice can be generated by different basis (good basis: short orthogonal vectors).

=== Idea

Use bad basis as public key and good basis as private key.

=== Problem

Find a non-zero vector with minimal norm according to a basis...

= Passkey

Way to sign in to app without password

Allows to avoid phishing

== Benefits

No password
resistant to attacks
faster and seamless login (biometric unlock)
user-friendly
sync across devices

== Limits and risks

depend on ecosystem
depend on account security
some passkeys cannot be transfered
risk of loss if user loses all devices
service adoption still evolving
not ideal for shared devices

device-bound passkeys are much harder to attack

= Quantum cryptography

Classic computer: bits (0-1)

Quantum computer: Qubit

== Properties

- superposition
  - infinite number of states
  - measurement: qubit collapses
- entanglement (qubit can be link to other) (2^n basis states !)

== Challenges

- collapsing
- qubits are very sensitive to environment

== Dangers

Asymetric cryptography is in danger !

Probability to fail when decrypting is small, but positive !!!

Length of key for post-quantum cryptography is bigger than for classical cryptography...

Theoritical security of the algorithm can be broken by the implementation of the protocol

== Cryptoagility

Rapid adaptation of new algorithm without disrupting structure of actual system

Goal: smooth transition to quantum area !

